insert into author (age, name, genre, id) values (23, "Mark Janel", "Anthology", 1); 
insert into author (age, name, genre, id) values (43, "Olivia Goy", "Horror", 2);
insert into author (age, name, genre, id) values (51, "Quartis Young", "Anthology", 3);
insert into author (age, name, genre, id) values (34, "Joana Nimar", "History", 4);
insert into author (age, name, genre, id) values (38, "Alicia Tom", "Anthology", 5);
insert into author (age, name, genre, id) values (56, "Katy Loin", "Anthology", 6);
insert into author (age, name, genre, id) values (23, "Wuth Troll", "Anthology", 7);
insert into author (age, name, genre, id) values (32, "Olivia Vancea", "Horror", 8);
insert into author (age, name, genre, id) values (54, "Liz Taylor", "Anthology", 9);
insert into author (age, name, genre, id) values (44, "Jenny Kal", "History", 10);
insert into author (age, name, genre, id) values (28, "Maruc Biel", "Anthology", 11);
insert into author (age, name, genre, id) values (26, "Katre Mun", "Anthology", 12);
insert into author (age, name, genre, id) values (43, "Ion Lion", "Anthology", 13);
insert into author (age, name, genre, id) values (43, "Olivia Tun", "Horror", 14);
insert into author (age, name, genre, id) values (51, "Alicia Thomanson", "Anthology", 15);
insert into author (age, name, genre, id) values (24, "Joana Leonte", "History", 16);
insert into author (age, name, genre, id) values (38, "Forel Rin", "Anthology", 17);
insert into author (age, name, genre, id) values (51, "Xan Kiu", "Anthology", 18);
insert into author (age, name, genre, id) values (43, "Viorel Gog", "Anthology", 19);
insert into author (age, name, genre, id) values (33, "Erat Murat", "Horror", 20);
insert into author (age, name, genre, id) values (54, "Connory Farel", "Anthology", 21);
insert into author (age, name, genre, id) values (24, "Kemal Ilias", "History", 22);
insert into author (age, name, genre, id) values (28, "Yldaz Sarun", "Anthology", 23);
insert into author (age, name, genre, id) values (50, "Sevne Bos", "Anthology", 24);
insert into author (age, name, genre, id) values (23, "Tylor Ruth", "Anthology", 25);
insert into author (age, name, genre, id) values (43, "Ramona Ro", "Horror", 26);
insert into author (age, name, genre, id) values (51, "Baris Giel", "Anthology", 27);
insert into author (age, name, genre, id) values (24, "Sandra Ostapenco", "History", 28);
insert into author (age, name, genre, id) values (39, "Maurice Call", "Anthology", 29);
insert into author (age, name, genre, id) values (56, "Sinco Mayo", "Anthology", 30);
insert into author (age, name, genre, id) values (23, "Nimar Nagu", "Anthology", 31);
insert into author (age, name, genre, id) values (33, "Leo Pol", "Horror", 32);
insert into author (age, name, genre, id) values (54, "Marquez Tooh", "Anthology", 33);
insert into author (age, name, genre, id) values (44, "Wix Sanel", "History", 34);
insert into author (age, name, genre, id) values (38, "Cordom Ball", "Anthology", 35);
insert into author (age, name, genre, id) values (26, "Matra Yong", "Anthology", 36);
insert into author (age, name, genre, id) values (43, "Cindra Well", "Anthology", 37);
insert into author (age, name, genre, id) values (33, "Liyra Jkir", "Horror", 38);
insert into author (age, name, genre, id) values (51, "Dfne Grigores", "Anthology", 39);
insert into author (age, name, genre, id) values (29, "Casmo Dir", "History", 40);
insert into author (age, name, genre, id) values (38, "Dundar Winchre", "Anthology", 41);
insert into author (age, name, genre, id) values (51, "Derf Ret", "Anthology", 42);
insert into author (age, name, genre, id) values (53, "Reltiop Vorit", "Anthology", 43);
insert into author (age, name, genre, id) values (33, "Kurmel Danar", "Horror", 44);
insert into author (age, name, genre, id) values (54, "Ritgiger Chriosf", "Anthology", 45);
insert into author (age, name, genre, id) values (24, "Alp Ran", "History", 46);
insert into author (age, name, genre, id) values (48, "Ulmean Gasim", "Anthology", 47);
insert into author (age, name, genre, id) values (23, "Nagir Turok", "Anthology", 48);
insert into author (age, name, genre, id) values (32, "Kiol Rathion", "Horror", 49);
insert into author (age, name, genre, id) values (51, "Murich Safir", "Anthology", 50);
insert into author (age, name, genre, id) values (44, "Gheorg Pariok", "History", 51);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-0134685991', 45.23, 'Effective Java', 1);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-0134670942', 29.37, 'Introduction to Java Programming', 1);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-0596009205', 49.67, 'Head First Java', 1);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-1790789870', 11.67, 'Learn Java in One Day', 2);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-0134802213', 39.50, 'Starting Out with Java', 3);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-0134462028', 31.95, 'Java Software Solutions', 3);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-0136520153', 31.99, 'Intro to Java Programming', 3);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-1118771334', 29.19, 'Data Structures and Algorithms in Java', 3);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-1492078005', 51.51, 'Head First Design Patterns', 4);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-1484256657', 44.99, 'Pro Spring MVC with WebFlux', 5);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-1517671273', 37.95, 'Elements of Programming Interviews in Java', 6);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-1492050049', 20.68, 'Learning Spark', 6);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-1260440232', 22.15, 'Java: The Complete Reference', 7);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-1617294631', 40.99, 'Natural Language Processing in Action', 7);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-1119619130', 56.07, 'OCP Oracle Certified Professional Java SE', 7);
INSERT INTO book (isbn, price, title, author_id) VALUES( '978-0134041674', 30.67, 'Absolute Java', 7);